#!/usr/bin/bash
# See knowlegebase article to config namecheap
# https://www.namecheap.com/support/knowledgebase/article.aspx/43/11/how-do-i-set-up-a-host-for-dynamic-dns
# make it executable `chmod +x ddns-update`
# move it path `mv ddns-update /usr/bin/`
# setup cronjob for every 15 minutes `crontab -e`
# */15 * * * * ddns-update >/dev/null 2>&1
# dont forget to change your own domain & password

LAST_IP_FILE="/tmp/last_ip"
WAIT=
QUIET=

while getopts "qfwh" flag; do
    case $flag in
        q|quiet) QUIET=1;;
        f|force) rm -f "$LAST_IP_FILE";;
        w|wait) WAIT=1;;
        h|help) echo "usage: $(basename $0)
            -q --quiet
            -f --force
            -w --wait
            -h --help"; exit 0;;
    esac
    lastflag="$flag"
    shift $((OPTIND - 1)); OPTIND=1
done

log() {
    errors="$2"
    xml="$3"

    if [ -n "$errors" ] || [ -z "$QUIET" ]; then
        echo "$1"
    fi | if [ "$xml" == 'xml' ] && which xmllint > /dev/null; then
        xmllint --format -
    else
        cat
    fi
}

# uncomment if you want internet connection check before running
while [ -n "$WAIT" ] && ! ping -c 1 -W 1 8.8.8.8 >/dev/null; do
    log "DDNS-UPDATE: Waiting internet connection.."
    sleep 2
done

last_ip=$(cat $LAST_IP_FILE 2>/dev/null)
log "DDNS-UPDATE: OK, Getting public IP address"
ip=$(curl -s http://dynamicdns.park-your-domain.com/getip)
if [ "$ip" == "$last_ip" ]; then
	log "IP Still same, no update needed."
	exit 0
fi

log "DDNS-UPDATE: Public IP is: $ip, Updating IP..."

source ~/.namecheap_file.sh

response=$(curl -s "https://dynamicdns.park-your-domain.com/update?host=$host&domain=$domain&password=$password&ip=$ip")
if which xmlstarlet > /dev/null; then
    errors=$(echo "$response" | xmlstarlet sel -t -m '//ErrCount' -v . -n)
else
    errors=$(echo "$response" | sed -r 's/.*<ErrCount>([0-9]+)<\/ErrCount>.*/\1/')
fi

log "$response" "$errors" 'xml'

echo $ip > $LAST_IP_FILE
exit 0
